### ISSUE TITLE
[SPIKE] Determine how to allow CI to run with non-master TSP

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/tenant-security-client-java#27]
Right now when CI runs it checks out the branch of the TSC-java but then always `master` of the TSP. This can be a problem when a PR depends on changes in both places, or a long running feature branch of the other.

AC:
* codependant features pass CI integration test runs
* CI integration test runs that require long running feature branches pass

**Comment by BobWall23** [comment]
Need to figure out how to determine branch names to use in CI. Code it into the branch name you are PRing? Or is there an input - a comment or the PR description?

When this is figured out, write a ticket to actually do the needful.

**Comment by cjyar** [comment]
We might be able to learn some lessons from the LD release workflow (in progress right now). It allows you to manually trigger the workflow and specify different versions of each repository to test against each other.

**Comment by cjyar** [comment]
Seems like we'll need to track metadata along a git branch, so we can point to a particular branch of another repo to run tests against. And when a branch merges to master, we probably want to clear that metadata, on the assumption that master should test against master. Here are some things I looked at:

- git attributes: Not intended for this purpose.
- git notes: This lets you attach arbitrary text to any git object (commit, tree, or blob). If you're attaching it to a tree or blob, the syntax is arcane. Most people have no experience with git notes. Because they're attached to git objects, they don't automatically carry forward on a branch. That means we'd have to write automation to do that, or automation to search backwards along the history of the branch before running CI.
- git subtree: Lets you sort of import another repo into this one. Doesn't seem like a good fit.
- git submodules: Lets you embed a reference to another repo into this one. Submodules are difficult to work with and cause lots of trouble, but we might be able to take some lessons from them.
- plain text file: We could designate a special text file in the repo. If it exists, it specifies the target branch to test against. On merge to master, automation could remove the file.

**Comment by skeet70** [comment]
What about using the PR description or title, since we primarily care about it at a PR level? Or a comment with a specific structure?

**Comment by cjyar** [comment]
- PR comment: We could use [this action](https://github.com/peter-evans/find-comment) to pretty easily retrieve comments on the PR. We could define a simple syntax like `++tenant_security_proxy: my-pr-branch`, and the workflow could parse that before doing the checkout action. If there are multiple comments that match the syntax, I guess we'd take the most recent.
- PR title: We'd probably have to use curl against the GitHub API to retrieve the PR title, but then we could follow a similar strategy as with a PR comment.

**Comment by cjyar** [comment]
We could even have CI post a comment reminding the user how to add the special branch syntax to a PR.

**Comment by cjyar** [comment]
++tenant_security_proxy: my-pr-branch
++tsp-system-test: my-other-branch

**Comment by cjyar** [comment]
{ "tenant_security_proxy": "my-pr-branch", "tsp-system-test": "my-other-branch" }

**Comment by cjyar** [comment]
ci[tenant_security_proxy=my-pr-branch, tsp-system-test=my-other-branch]

**Comment by cjyar** [comment]
Plan:
- When a PR is created, use https://github.com/marketplace/actions/create-or-update-comment to post a comment on the PR explaining the syntax to use. Syntax is any comment containing the magic string `CI_branches` and a json object. Other text in the comment will be ignored. The json object has repository names as its keys, and git refs as its values.
- If we're on a PR branch, CI uses https://github.com/marketplace/actions/find-comment to scan the PR for comments containing the magic string.
    - If a matching comment is found, parse it using `echo ${{ comment }} | sed -e 's,^[^{]*,,' -e 's,[^}]*$,,' | jq ...`. This strips out text before the first `{` and after the last `}`. So you can use triple backquotes or explanatory text or whatever else you want.
    - Use `jq` to extract key names and fail the workflow if an unrecognized repository is present.
    - Use `jq` to extract a git ref for each repo we care about.
    - Use https://github.com/marketplace/actions/create-or-update-comment to post either `eyes` or `confused` as an emoji reaction on the comment.
- Check out the indicated refs of the repositories.

**Comment by BobWall23** [comment]
Not sure I understand the first `create-or-update-comment` bullet. That's just a reminder to the creator of the PR about what to put in a comment to make it work? Seems unnecessary.

Otherwise, LGTM

**Comment by cjyar** [comment]
Yeah, that was the intent. If we don't like that reminder, we can disable it.
